### ISSUE TITLE
Example code : Dates are mutable

### ISSUE THREAD

**Issue by woot4moo** [bparry02/jboss-modules-demo#2]
```
 public String getMonthShortText(Date date) {
        return MonthDay.fromDateFields(date).monthOfYear().getAsShortText();
    }
```

Because Date is mutable it would be good to demonstrate this in the code.  However, if this were Java 8 the Joda Time library could be discarded as well.

**Comment by bparry02** [comment]
Thanks for the feedback. This project is supposed to be a demonstration of how class loading works with WildFly and JBoss EAP. My example invokes the joda-time library because I needed an example that invokes a third-party library. My code isn't really trying to do anything with Date objects, it's just an example that calls org.joda.time.MonthDay.
